version: 2.1
jobs:
  ci:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup QEMU
          command: docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - run:
          name: Dagger Pipeline
          command: go run ci/main.go
workflows:
  test:
    jobs:
      - ci