version: 2.1
jobs:
  cicd:
    machine: true
    resource_class: kpenfound/self
    steps:
      - checkout
      - run:
          name: Configure Docker
          command: |
            export DOCKER_USERNAME=$(./vault kv get -tls-skip-verify -field=docker_username kv/hello-nomad)
            export DOCKER_PASSWORD=$(./vault kv get -tls-skip-verify -field=docker_password kv/hello-nomad)
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - run:
          name: Dagger Pipeline
          command: go run ci/main.go
workflows:
  cicd:
    jobs:
      - cicd