version: 2.1
orbs:
  circleci-tailscale: threecomma/circleci-tailscale@1.0.0

jobs:
  cicd:
    docker:
      - image: cimg/go:1.19
    parameters:
      tailscale-auth-key:
        type: env_var_name
        default: TAILSCALE_AUTH_KEY
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup QEMU
          command: docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - circleci-tailscale/connect
      - run:
          name: Docker Login
          command: |
            curl -o vault.zip https://releases.hashicorp.com/vault/1.12.1/vault_1.12.1_linux_amd64.zip
            unzip vault.zip
            export DOCKER_USERNAME=$(./vault kv get -tls-skip-verify -field=docker_username kv/hello-nomad)
            export DOCKER_PASSWORD=$(./vault kv get -tls-skip-verify -field=docker_password kv/hello-nomad)
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: # Docker login
          name: Dagger Pipeline
          command: go run ci/main.go
workflows:
  cicd:
    jobs:
      - cicd