name: test
on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Setup QEMU
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - name: Dagger Pipeline #Docker login
      - run: |
        go run ci/main.go