name: cicd
on:
  push:
    branches: [main]

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Get Registry Credentials
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          tlsSkipVerify: true # no option for tls server name
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/hello-nomad docker_username | DOCKER_USERNAME
            kv/hello-nomad docker_password | DOCKER_PASSWORD
      - name: Docker Login
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - uses: actions/checkout@v3
      - name: Setup QEMU
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - name: Dagger Pipeline
        run: |
          go run ci/main.go